"""Fixed, reviewed help content for the in-app guide: feature tours, business concepts and quick questions.

Everything here is written by hand. Examples use clearly illustrative numbers (never the owner's data). Learning
links are SEARCH links (YouTube / Coursera search results), never specific videos or courses we have not checked.
"""

from __future__ import annotations

from urllib.parse import quote_plus

# go: where "Show me" takes the user. tab = a tab on the investigation page; anchor = an element id on that page;
# route = a top-level page.
FEATURES: list[dict] = [
    {"id": "start", "go": {"route": "/"},
     "title": {"ar": "ابدأ تحقيق", "en": "Start an investigation"},
     "what": {"ar": "التحقيق هو المكان اللي بنفهم فيه فلوسك بتروح فين.",
              "en": "An investigation is where Ribhiya works out where your money goes."},
     "steps": {"ar": ["من الصفحة الرئيسية اكتب اسم النشاط واختار العملة.", "اضغط «ابدأ تحقيق جديد».",
                      "جاوب ٣ أسئلة قصيرة عن نشاطك."],
               "en": ["On Home, type your business name and pick the currency.", "Click “Start a new investigation”.",
                      "Answer three short questions about your business."]},
     "kw": ["ابدا", "ابدأ", "تحقيق جديد", "اول خطوه", "start", "begin", "new investigation", "first step"]},
    {"id": "upload", "go": {"tab": "files"},
     "title": {"ar": "إزاي أرفع البيانات", "en": "How to load your data"},
     "what": {"ar": "ارفع ملفات شغلك زي ما هي. «ربحية» بتقرا الأعمدة لوحدها.",
              "en": "Upload your files as they are. Ribhiya reads the columns by itself."},
     "steps": {"ar": ["الأهم: ملف المبيعات أو الطلبات (تاريخ، منتج، كمية، سعر).",
                      "بعده: تكلفة المنتجات، فواتير المصاريف (تغليف، شحن، رسوم)، وكشف الشحن والمرتجعات لو موجودين.",
                      "ينفع CSV أو Excel (كل الشيتات) أو PDF فيه نص. العناوين بالعربي عادي.",
                      "لو ملف ما اتقراش، اضغط «ظبّط الأعمدة» وقولها كل عمود معناه إيه. هتفتكر الشكل ده بعد كده.",
                      "مش لازم كل الملفات من الأول. «اعمل ده دلوقتي» هتطلب اللي ناقص بس."],
               "en": ["Most important: your sales or orders file (date, product, quantity, price).",
                      "Then: product costs, expense invoices (packaging, shipping, fees), and courier and returns "
                      "statements if you have them.",
                      "CSV, Excel (all sheets) or a PDF with text. Arabic column names are fine.",
                      "If a file isn't read, click “Fix columns” and say what each column means. It remembers that layout.",
                      "You don't need every file up front. “Do this now” asks only for what's missing."]},
     "kw": ["ارفع", "رفع", "تحميل", "ملف", "ملفات", "بيانات", "اكسل", "excel", "csv", "pdf", "اعمده", "عمود",
            "upload", "load", "data", "file", "files", "columns", "import", "template", "قالب"]},
    {"id": "do_now", "go": {"anchor": "do-now"},
     "title": {"ar": "كارت «اعمل ده دلوقتي»", "en": "The “Do this now” card"},
     "what": {"ar": "كارت واحد فيه أهم خطوة دلوقتي، عشان ما تتوهش.",
              "en": "One card with the single most useful step right now, so you never get lost."},
     "steps": {"ar": ["جاوب السؤال أو ارفع الملف المطلوب.", "مش عندك الملف؟ اضغط «معنديش الملف ده» والتحليل هيكمل.",
                      "«ليه؟» بتقولك السؤال ده مهم ليه."],
               "en": ["Answer the question or upload the file it asks for.",
                      "Don't have the file? Click “I don't have this file” and the analysis continues.",
                      "“Why?” explains why the question matters."]},
     "kw": ["اعمل ده", "الخطوه الجايه", "اعمل ايه", "تايه", "do this now", "next step", "what next", "lost", "stuck"]},
    {"id": "leak", "go": {"anchor": "leak"},
     "title": {"ar": "«اللي لقيته»: التسريب", "en": "“What I found”: the leak"},
     "what": {"ar": "أكبر تكلفة زادت على كل طلب بين آخر شهرين، وكام بتخسرك في الشهر.",
              "en": "The cost that grew the most per order between your last two months, and what it costs you a month."},
     "steps": {"ar": ["الرسم بيقارن تكلفة كل طلب بند بند بين الشهرين.", "«اشرحلي» بتوريك السبب والأدلة والحلول.",
                      "«لقيت كمان» فيها التسريبات التانية."],
               "en": ["The chart compares the cost per order, item by item, across the two months.",
                      "“Explain” shows the reason, the evidence and options.", "“Also found” lists the other leaks."]},
     "kw": ["لقيته", "تسريب", "رسم", "رسمه", "رسومات", "الرسومات", "جراف", "الشارت", "leak", "found", "chart", "graph", "finding"]},
    {"id": "products", "go": {"tab": "products"},
     "title": {"ar": "ربح المنتجات والطلبات", "en": "Product and order profit"},
     "what": {"ar": "كل منتج وكل طلب بيسيبلك كام بعد كل تكاليفه.",
              "en": "What each product and each order leaves you after all its costs."},
     "steps": {"ar": ["جدول المنتجات: المبيعات واللي بيفضل وهامش كل منتج.",
                      "«طلبات خسرانة»: الطلبات اللي تكلفتها أكتر من اللي دفعه العميل.",
                      "«فعلي» يعني من فاتورة الطلب نفسه، و«تقدير» يعني فاتورة شهرية اتوزعت على الطلبات."],
               "en": ["Products table: sales, what's left and the margin of each product.",
                      "“Orders that lost money”: orders whose costs exceeded what the customer paid.",
                      "“Actual” means from that order's own record; “allocated (estimate)” means a monthly invoice "
                      "shared across orders."]},
     "kw": ["منتج", "منتجات", "طلبات خسرانه", "هامش", "product", "products", "orders", "margin", "losing", "lost money"]},
    {"id": "whatif", "go": {"tab": "whatif"},
     "title": {"ar": "«لو غيّرت…؟» (الحاسبة)", "en": "“What if…?” (simulator)"},
     "what": {"ar": "جرّب تغيير قبل ما تعمله: سعر، تكلفة تغليف، شحن مجاني. ملفاتك ما بتتغيّرش.",
              "en": "Try a change before you make it: a price, a packaging cost, free shipping. Your files never change."},
     "steps": {"ar": ["افتح تبويب «لو غيّرت…».", "اختار التغيير (مثلاً تكلفة التغليف لكل طلب) واكتب الرقم الجديد.",
                      "اضغط «احسب». النتيجة تقدير، ومكتوب جنبها الافتراضات.",
                      "عجبك؟ احفظه كتجربة عشان نقيسه بعدين بالأرقام الحقيقية."],
               "en": ["Open the “What if” tab.", "Pick a change (for example packaging cost per order) and type the new value.",
                      "Click “Calculate”. The result is a projection, with its assumptions listed.",
                      "Like it? Save it as an experiment so we can measure it later with real numbers."]},
     "kw": ["لو غيرت", "حاسبه", "سيناريو", "تجربه", "سعر", "what if", "whatif", "simulat", "scenario", "calculate",
            "price change"]},
    {"id": "suppliers", "go": {"tab": "suppliers"},
     "title": {"ar": "الموردين وعروض الأسعار", "en": "Suppliers and quotes"},
     "what": {"ar": "اطلب أسعار أرخص لنفس الجودة، وقارن العروض صح.",
              "en": "Ask for cheaper prices at the same quality, and compare quotes fairly."},
     "steps": {"ar": ["اضغط «اطلب أسعار أرخص» من «اللي لقيته».", "كمّل بيانات الطلب، راجع الإيميل، ووافق عليه.",
                      "ابعته (لو الإيميل متظبط) أو انسخه وابعته بنفسك. مفيش حاجة بتتبعت من غير موافقتك.",
                      "لما الرد يوصل ضيفه كعرض سعر. بنقارن بس العروض الحقيقية بنفس المواصفات، ونحسب أقل كمية للطلب."],
               "en": ["Click “Get cheaper prices” in “What I found”.", "Fill in the brief, review the email and approve it.",
                      "Send it (if email is set up) or copy it and send it yourself. Nothing is sent without your approval.",
                      "When the reply arrives, add it as a quote. Only real quotes for the same specification are "
                      "compared, including minimum order quantities."]},
     "kw": ["مورد", "موردين", "عرض سعر", "عروض", "ارخص", "supplier", "suppliers", "quote", "quotes", "cheaper", "moq",
            "اقل كميه"]},
    {"id": "results", "go": {"tab": "results"},
     "title": {"ar": "قيس النتيجة", "en": "Measure the result"},
     "what": {"ar": "بعد ما تنفّذ تغيير، نقارن قبل وبعد بالأرقام الحقيقية.",
              "en": "After you make a change, compare before and after with real numbers."},
     "steps": {"ar": ["في «النتايج» سجّل تاريخ بداية التغيير.", "ارفع ملفات الشهر اللي بعده.",
                      "اضغط «قيس النتيجة». بنقولك اللي اتغيّر فعلاً، من غير ما ندّعي إن التغيير هو السبب أكيد."],
               "en": ["In “Results”, set the date you started the change.", "Upload the following month's files.",
                      "Click “Check the result”. It shows what actually changed, without claiming the change caused it."]},
     "kw": ["نتيجه", "النتايج", "قيس", "قبل وبعد", "result", "results", "measure", "verify", "before and after"]},
    {"id": "ask", "go": None,
     "title": {"ar": "اسأل عن أرقامك", "en": "Ask about your numbers"},
     "what": {"ar": "جوه أي تحقيق، الشات ده بيجاوب من أرقام التحقيق نفسه.",
              "en": "Inside an investigation, this chat answers from that investigation's own numbers."},
     "steps": {"ar": ["افتح تحقيقك، وبعدين افتح «اتكلم مع ربحية».",
                      "اسأل: «ليه ربحي قلّ؟»، «أعمل إيه دلوقتي؟»، «إيه الناقص؟».",
                      "تحت كل إجابة مكتوب هي جاية منين، وأي رقم مش طالع من الحسابات بيتعلّم عليه."],
               "en": ["Open your investigation, then open “Chat with Ribhiya”.",
                      "Ask: “Why is my profit down?”, “What should I do now?”, “What's missing?”.",
                      "Each answer says where it came from, and any figure not in the calculations is flagged."]},
     "kw": ["اسال عن", "ارقامي", "my numbers", "ask tab", "advisor"]},
    {"id": "memory", "go": {"tab": "files"},
     "title": {"ar": "«ربحية» فاكرة إيه", "en": "What Ribhiya remembers"},
     "what": {"ar": "بتفتكر بس اللي إنت أكدته، زي شكل أعمدة ملفاتك. وتقدر تمسحه.",
              "en": "Only what you confirmed, like your files' column layouts. You can delete it."},
     "steps": {"ar": ["آخر تبويب «الملفات» فيه «اللي ربحية فاكراه».", "اضغط «انسى» لأي حاجة."],
               "en": ["At the bottom of the “Files” tab: “What Ribhiya remembers”.", "Click “Forget” on anything."]},
     "kw": ["فاكره", "ذاكره", "تتعلم", "بتتعلم", "بتفتكر", "remember", "memory", "learn", "forget"]},
    {"id": "safety", "go": None,
     "title": {"ar": "الخصوصية والأمان", "en": "Privacy and safety"},
     "what": {"ar": "ملفاتك بتفضل عندك. الأرقام من الحسابات مش من الذكاء الاصطناعي، ومفيش إرسال من غير موافقتك.",
              "en": "Your files stay with you. Figures come from calculations, not AI, and nothing is sent without "
                    "your approval."},
     "steps": {"ar": ["الملفات بتتحفظ على جهازك أو السيرفر بتاعك بس.",
                      "الذكاء الاصطناعي بيشرح بس؛ الأرقام كلها محسوبة.",
                      "أي إيميل لمورد لازم توافق عليه الأول.", "⏻ بيوقف كل حاجة في أي وقت."],
               "en": ["Files are stored only on your computer or your own server.",
                      "AI only explains; every figure is calculated.",
                      "Any email to a supplier needs your approval first.", "⏻ stops everything at any time."]},
     "kw": ["خصوصيه", "امان", "بياناتي", "اوقف", "ايقاف", "الارسال", "stop sending", "emergency", "pause", "privacy", "safe", "security", "secure", "my data"]},
]

# Business concepts. `feature` = where to see it in Ribhiya. `q` = search terms for learning links.
CONCEPTS: list[dict] = [
    {"id": "profit_vs_sales", "feature": "leak",
     "title": {"ar": "المبيعات مش الربح", "en": "Sales are not profit"},
     "simple": {"ar": "المبيعات هي اللي دخل. الربح هو اللي فضل بعد كل التكاليف.",
                "en": "Sales are what came in. Profit is what's left after all costs."},
     "example": {"ar": "مثال: بعت بـ١٠٠٬٠٠٠ وصرفت ٩٠٬٠٠٠، يبقى ربحك ١٠٬٠٠٠ بس.",
                 "en": "Example: you sold 100,000 and spent 90,000, so you made only 10,000."},
     "why": {"ar": "ممكن المبيعات تزيد والربح يقلّ لو التكاليف زادت أسرع.",
             "en": "Sales can grow while profit shrinks if costs grow faster."},
     "q": {"ar": "الفرق بين الإيرادات والربح للمشروعات الصغيرة", "en": "revenue vs profit small business explained"},
     "kw": ["مبيعات", "ربح", "ايراد", "sales", "profit", "revenue"]},
    {"id": "contribution", "feature": "products",
     "title": {"ar": "اللي بيفضل من كل طلب (هامش المساهمة)", "en": "What each order leaves (contribution margin)"},
     "simple": {"ar": "سعر الطلب ناقص تكاليفه المباشرة: المنتج والتغليف والشحن والرسوم والخصم.",
                "en": "The order's price minus its direct costs: product, packaging, shipping, fees and discount."},
     "example": {"ar": "مثال: طلب بـ٤٠٠، تكاليفه ٢٩٠، يبقى بيسيبلك ١١٠ تغطي بيها الإيجار والمرتبات.",
                 "en": "Example: a 400 order with 290 of costs leaves 110 to cover rent and salaries."},
     "why": {"ar": "لو الرقم ده صغير، كل طلب زيادة مش هيفرق كتير.", "en": "If it's small, more orders won't help much."},
     "q": {"ar": "هامش المساهمة شرح", "en": "contribution margin explained"},
     "kw": ["مساهمه", "بيفضل", "contribution", "per order", "لكل طلب"]},
    {"id": "gross_margin", "feature": "products",
     "title": {"ar": "هامش الربح الإجمالي", "en": "Gross margin"},
     "simple": {"ar": "نسبة اللي بيفضل من السعر بعد تكلفة المنتج نفسه.",
                "en": "The share of the price left after the cost of the product itself."},
     "example": {"ar": "مثال: بتبيع بـ٢٠٠ والتكلفة ١٢٠، الهامش ٤٠٪.", "en": "Example: sell at 200, cost 120, margin 40%."},
     "why": {"ar": "بيوضح أنهي منتجات تستاهل تركّز عليها.", "en": "Shows which products deserve your focus."},
     "q": {"ar": "هامش الربح الإجمالي حساب", "en": "gross margin how to calculate"},
     "kw": ["هامش", "نسبه الربح", "margin", "gross"]},
    {"id": "cogs", "feature": "upload",
     "title": {"ar": "تكلفة البضاعة", "en": "Cost of goods (COGS)"},
     "simple": {"ar": "اللي بتدفعه عشان المنتج نفسه: شراء أو خامات وتصنيع.",
                "en": "What you pay for the product itself: purchase or materials and making."},
     "example": {"ar": "مثال: الكريم بيتكلف ٩٨ خامات وتعبئة، ده تكلفة البضاعة.",
                 "en": "Example: a cream costs 98 in materials and filling; that's its COGS."},
     "why": {"ar": "من غيرها مستحيل تعرف المنتج بيكسب ولا لأ.", "en": "Without it you can't tell if a product makes money."},
     "q": {"ar": "تكلفة البضاعة المباعة شرح مبسط", "en": "cost of goods sold explained simply"},
     "kw": ["تكلفه البضاعه", "تكلفه المنتج", "خامات", "cogs", "cost of goods", "unit cost"]},
    {"id": "fixed_variable", "feature": "leak",
     "title": {"ar": "تكاليف ثابتة ومتغيّرة", "en": "Fixed vs variable costs"},
     "simple": {"ar": "الثابتة ما بتتغيّرش مع عدد الطلبات (إيجار، مرتبات). المتغيّرة بتزيد مع كل طلب (تغليف، شحن).",
                "en": "Fixed costs don't change with orders (rent, salaries). Variable costs grow with every order "
                      "(packaging, shipping)."},
     "example": {"ar": "مثال: الإيجار ١٠٬٠٠٠ ثابت، والتغليف ١٨ على كل طلب.",
                 "en": "Example: rent 10,000 is fixed; packaging 18 per order is variable."},
     "why": {"ar": "المتغيّرة بتأكل من كل طلب، فتوفيرها بيكبر مع النمو.",
             "en": "Variable costs eat into every order, so savings grow as you grow."},
     "q": {"ar": "التكاليف الثابتة والمتغيرة", "en": "fixed vs variable costs small business"},
     "kw": ["ثابته", "متغيره", "fixed", "variable", "overhead"]},
    {"id": "break_even", "feature": "whatif",
     "title": {"ar": "نقطة التعادل", "en": "Break-even point"},
     "simple": {"ar": "عدد الطلبات اللي محتاجه عشان تغطي التكاليف الثابتة، من غير ربح ولا خسارة.",
                "en": "How many orders you need to cover fixed costs, with no profit and no loss."},
     "example": {"ar": "مثال: ثابت ٢٠٬٠٠٠ وكل طلب بيسيب ١٠٠، يبقى محتاج ٢٠٠ طلب في الشهر.",
                 "en": "Example: 20,000 fixed and 100 left per order means 200 orders a month."},
     "why": {"ar": "بيقولك هدف واضح للمبيعات.", "en": "Gives you a clear sales target."},
     "q": {"ar": "نقطة التعادل للمشروع الصغير", "en": "break even point small business"},
     "kw": ["تعادل", "break even", "breakeven"]},
    {"id": "pricing", "feature": "whatif",
     "title": {"ar": "التسعير", "en": "Pricing"},
     "simple": {"ar": "السعر لازم يغطي كل تكاليف الطلب ويسيب ربح، مش بس تكلفة المنتج.",
                "en": "A price must cover all of the order's costs and leave profit, not just the product cost."},
     "example": {"ar": "مثال: زيادة ٥٪ على منتج بيسيب ٢٠٪ ممكن تزوّد ربحه الربع لو المبيعات ما قلّتش.",
                 "en": "Example: +5% on a product with a 20% margin can lift its profit by a quarter if sales hold."},
     "why": {"ar": "تغيير صغير في السعر بيأثر جامد على الربح. جرّبه في «لو غيّرت».",
             "en": "A small price change has a big effect on profit. Try it in “What if”."},
     "q": {"ar": "تسعير المنتجات للمشروعات الصغيرة", "en": "how to price products small business"},
     "kw": ["تسعير", "سعر", "اسعار", "pricing", "price"]},
    {"id": "discounts", "feature": "leak",
     "title": {"ar": "الخصومات وأثرها", "en": "Discounts and their real cost"},
     "simple": {"ar": "الخصم بيتخصم من ربحك، مش من المبيعات بس.",
                "en": "A discount comes out of your profit, not just your sales."},
     "example": {"ar": "مثال: طلب بيسيب ١٠٠، خصم ٥٠ بيقص ربحه النص.",
                 "en": "Example: an order leaving 100 loses half its profit to a 50 discount."},
     "why": {"ar": "خلّي الخصم بهدف: حد أدنى للطلب أو منتجات راكدة.",
             "en": "Give discounts a purpose: a minimum basket or slow-moving items."},
     "q": {"ar": "تأثير الخصومات على الربح", "en": "how discounts affect profit margin"},
     "kw": ["خصم", "خصومات", "عروض", "discount", "discounts", "promotion"]},
    {"id": "returns", "feature": "leak",
     "title": {"ar": "تكلفة المرتجعات", "en": "The cost of returns"},
     "simple": {"ar": "المرتجع بيكلّفك الفلوس اللي رجعت والشحن مرتين وساعات المنتج نفسه.",
                "en": "A return costs the refund, shipping twice, and sometimes the product itself."},
     "example": {"ar": "مثال: لو ٥٪ من الطلبات بترجع، ده بيوزّع تكلفة على كل الطلبات.",
                 "en": "Example: if 5% of orders come back, that cost spreads across all orders."},
     "why": {"ar": "سجّل سبب كل مرتجع؛ السبب هو اللي بيقولك تصلّح إيه.",
             "en": "Record the reason for each return; it tells you what to fix."},
     "q": {"ar": "تقليل المرتجعات في التجارة الإلكترونية", "en": "reduce ecommerce returns"},
     "kw": ["مرتجع", "مرتجعات", "استرجاع", "return", "returns", "refund"]},
    {"id": "cash_flow", "feature": "leak",
     "title": {"ar": "الكاش مش الربح", "en": "Cash flow is not profit"},
     "simple": {"ar": "ممكن تكون كسبان على الورق ومعكش كاش، لو الفلوس متأخرة عند العملاء أو في المخزون.",
                "en": "You can be profitable on paper and still have no cash if money is stuck with customers or in stock."},
     "example": {"ar": "مثال: بعت بـ٥٠٬٠٠٠ آجل، الربح موجود بس الكاش لسه ما دخلش.",
                 "en": "Example: you sold 50,000 on credit; the profit is there but the cash isn't."},
     "why": {"ar": "الكاش هو اللي بيدفع المرتبات والموردين، فتابع الفلوس اللي ليك برّه كمان.",
             "en": "Cash is what pays salaries and suppliers, so keep an eye on money still owed to you."},
     "q": {"ar": "التدفق النقدي للمشروعات الصغيرة", "en": "cash flow management small business"},
     "kw": ["كاش", "الكاش", "سيوله", "تدفق", "cash", "cash flow", "liquidity"]},
    {"id": "moq_inventory", "feature": "suppliers",
     "title": {"ar": "المخزون وأقل كمية للطلب", "en": "Stock and minimum order quantity"},
     "simple": {"ar": "السعر الأرخص مع كمية كبيرة ممكن يحبس فلوسك في بضاعة مش محتاجها.",
                "en": "A cheaper price with a big minimum can lock your cash in stock you don't need yet."},
     "example": {"ar": "مثال: ١١ للقطعة بس لازم ١٠٠٠ قطعة، وإنت محتاج ١٤٠ بس.",
                 "en": "Example: 11 per unit but a minimum of 1,000, when you need only 140."},
     "why": {"ar": "قارن تكلفة القطعة اللي محتاجها فعلاً، مش سعر القطعة بس.",
             "en": "Compare the cost per unit you actually need, not just the unit price."},
     "q": {"ar": "إدارة المخزون للمشروعات الصغيرة", "en": "inventory management minimum order quantity"},
     "kw": ["مخزون", "اقل كميه", "كميه", "inventory", "stock", "moq", "minimum order"]},
    {"id": "aov_cac", "feature": "products",
     "title": {"ar": "متوسط الطلب وتكلفة جلب العميل", "en": "Average order value and customer cost"},
     "simple": {"ar": "متوسط الطلب = المبيعات ÷ عدد الطلبات. تكلفة جلب العميل = الإعلانات ÷ العملاء الجداد.",
                "en": "Average order = sales ÷ orders. Customer acquisition cost = ads ÷ new customers."},
     "example": {"ar": "مثال: لو العميل بيتكلف ١٥٠ إعلانات وطلبه بيسيب ١٠٠، إنت خسران لحد ما يرجع يشتري.",
                 "en": "Example: if a customer costs 150 in ads and their order leaves 100, you lose until they buy again."},
     "why": {"ar": "يساعدك تقرر تصرف كام على الإعلانات.", "en": "Helps you decide how much to spend on ads."},
     "q": {"ar": "متوسط قيمة الطلب وتكلفة اكتساب العميل", "en": "average order value customer acquisition cost"},
     "kw": ["متوسط الطلب", "اعلانات", "تسويق", "aov", "cac", "ads", "marketing", "acquisition"]},
    {"id": "experiments", "feature": "results",
     "title": {"ar": "جرّب وقيس", "en": "Test and measure"},
     "simple": {"ar": "غيّر حاجة واحدة، وقارن قبل وبعد بأرقام حقيقية.",
                "en": "Change one thing, then compare before and after with real numbers."},
     "example": {"ar": "مثال: غيّرت مورد التغليف أول الشهر، قارن تكلفة التغليف لكل طلب بالشهر اللي قبله.",
                 "en": "Example: you switched packaging supplier on the 1st; compare packaging per order with the month before."},
     "why": {"ar": "التغيير اللي ما اتقاسش ممكن يكون مضر من غير ما تعرف.",
             "en": "An unmeasured change might be hurting you without you knowing."},
     "q": {"ar": "قياس نتائج التغيير في المشروع", "en": "measure business experiment before after"},
     "kw": ["قياس", "تجربه", "قبل وبعد", "measure", "experiment", "test"]},
]

# Starter questions on the home page (inside an investigation the UI shows stage-aware ones instead).
QUICK: dict[str, list[str]] = {
    "ar": ["أبدأ منين؟", "إزاي أرفع البيانات؟", "إزاي أجرّب «لو غيّرت»؟", "إزاي أطلب أسعار من موردين؟",
           "يعني إيه هامش المساهمة؟"],
    "en": ["Where do I start?", "How do I load my data?", "How do I try a what-if?", "How do I get supplier quotes?",
           "What is contribution margin?"],
}

INTENTS: dict[str, list[str]] = {
    "solutions": ["حلول", "حل", "اقترح", "انصحني", "اعمل ايه عشان", "اصلحها", "اوفر", "اكسب اكتر", "suggest", "solution",
                  "what can i do", "fix it", "fix this",
                  "solutions", "advice", "improve", "save money"],
    "feedback": ["اقتراح", "فكره", "رايي", "رأيي", "تقييم", "عطل", "ميزه", "feedback", "review", "idea",
                 "feature request", "bug", "complain", "suggestion"],
    "learn": ["كورس", "كورسات", "يوتيوب", "فيديو", "اتعلم", "course", "courses", "youtube", "video", "learn", "tutorial"],
    "tour": ["جوله", "شرح التطبيق", "ازاي استخدم", "بيعمل ايه", "tour", "how to use", "guide me", "walkthrough",
             "what can you do", "تقدر تعمل ايه"],
}


def learn_links(c: dict, lang: str) -> list[dict]:
    q = c["q"][lang]
    yt = "https://www.youtube.com/results?search_query=" + quote_plus(q)
    co = "https://www.coursera.org/search?query=" + quote_plus(c["q"]["en"])
    return [{"kind": "youtube", "label": "YouTube" if lang == "en" else "يوتيوب", "url": yt},
            {"kind": "course", "label": "Coursera", "url": co}]


def public(lang: str) -> dict:
    """The content the UI renders (no keyword lists)."""
    return {
        "features": [{"id": f["id"], "go": f["go"], "title": f["title"][lang], "what": f["what"][lang],
                      "steps": f["steps"][lang]} for f in FEATURES],
        "concepts": [{"id": c["id"], "feature": c["feature"], "title": c["title"][lang], "simple": c["simple"][lang],
                      "example": c["example"][lang], "why": c["why"][lang], "links": learn_links(c, lang)}
                     for c in CONCEPTS],
        "quick": QUICK[lang],
        "links_note": ("روابط بحث في يوتيوب وكورسيرا؛ «ربحية» ما اختارتش ولا راجعت فيديو معيّن."
                       if lang == "ar" else
                       "Search links on YouTube and Coursera; Ribhiya didn't pick or review a specific video."),
    }
